# .project metadata for CloudEvents
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "cloudevents"
name: "CloudEvents"
description: "Standardizing common eventing metadata and their location to help with event identification and routing."
type: "project"
project_lead: "duglin"
slack_channels:
  - name: "#cloudevents"
    link: "https://cloud-native.slack.com/messages/cloudevents"
    primary: true
  - name: "#cloudeventssdk"
    link: "https://cloud-native.slack.com/messages/cloudeventssdk"

maturity_log:
  - phase: "graduated"
    date: "2024-01-25T00:00:00Z"
    issue: "https://github.com/cncf/toc/issues/1590"

repositories:
  - url: "https://github.com/cloudevents/spec"
    primary: true
    # tags: [core, sig-apps] # Optional
  - url: "https://github.com/cloudevents/cloudevents-web"
  - url: "https://github.com/cloudevents/conformance"
  - url: "https://github.com/cloudevents/sdk-csharp"
  - url: "https://github.com/cloudevents/sdk-go"
  - url: "https://github.com/cloudevents/sdk-java"
  - url: "https://github.com/cloudevents/sdk-javascript"
  - url: "https://github.com/cloudevents/sdk-kotlin"
  - url: "https://github.com/cloudevents/sdk-php"
  - url: "https://github.com/cloudevents/sdk-powershell"
  - url: "https://github.com/cloudevents/sdk-python"
  - url: "https://github.com/cloudevents/sdk-ruby"
  - url: "https://github.com/cloudevents/sdk-rust"

website: "https://cloudevents.io/"

artwork: "https://github.com/cncf/artwork/blob/main/projects/cloudevents/stacked/color/cloudevents-stacked-color.png?raw=true"

# TODO: Add ADOPTERS.md if your project tracks adopters
adopters:
  path: "https://cloudevents.io/"

# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "cloudevents/spec"

social:
  twitter: "https://twitter.com/cloudeventsio"

security:
  policy:
    path: "https://github.com/cloudevents/spec#security-concerns"
  # contact:
    # advisory_url: "https://github.com/cloudevents/spec/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/cloudevents/spec/blob/main/docs/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/cncf/foundation/blob/main/code-of-conduct.md"

legal:
  license:
    path: "https://github.com/cloudevents/spec/blob/main/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/cloudevents/spec/blob/main/README.md"

landscape:
  category: "App Definition and Development"
  subcategory: "Streaming & Messaging"

# CLOMonitor Score: 99/100
# Documentation: 100 | License: 100 | Best Practices: 89 | Security: 100
